// Lists a docs folder's own files (skipping its index/README doc) as
// sidebar doc ids, ordered by each file's `sidebar_position` frontmatter
// (falling back to alphabetical for files without one).
//
// Note: `{ type: 'autogenerated', dirName }` placed as a bare item does NOT
// wrap a folder into a category using its own index doc as the link — it
// just flattens the folder's contents (index doc included) as plain
// siblings at that position. That "self-contained folder" convention only
// applies when the *entire* sidebar is autogenerated top-down and a
// directory is discovered as a subdirectory of some other autogenerated
// scope, not when `dirName` itself points straight at the folder. So a
// category that wraps a folder under its own index doc (via `link`) needs
// its `items` built explicitly, excluding that index doc — that's what
// this does, while still requiring no manual sidebars.js edit as files are
// added/removed/reordered in the folder.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

function parseSidebarPosition(content) {
  const m = content.match(/^sidebar_position:\s*"?(-?\d+(?:\.\d+)?)"?/m);
  return m ? Number(m[1]) : null;
}

// Mirrors Docusaurus's DefaultNumberPrefixParser so generated doc ids match
// the ids Docusaurus assigns after stripping filename number prefixes
// (e.g. '1-introduction.md' => doc id '.../introduction').
const IGNORED_PREFIX_PATTERN = /^\d+[-_.]\d+/;
const NUMBER_PREFIX_PATTERN = /^(?:\d+)\s*[-_.]+\s*([^-_.\s].*)$/;

function stripNumberPrefix(filename) {
  if (IGNORED_PREFIX_PATTERN.test(filename)) return filename;
  const match = NUMBER_PREFIX_PATTERN.exec(filename);
  return match ? match[1] : filename;
}

/**
 * @param {string} docPrefix Doc-id of the folder, e.g. 'drivers/.../docs'.
 */
export function generateFolderSidebarItems(docPrefix) {
  const dir = path.join(ROOT, 'docs', ...docPrefix.split('/'));
  if (!fs.existsSync(dir)) return [];

  const entries = fs.readdirSync(dir).filter((f) => {
    if (!/\.mdx?$/.test(f)) return false;
    const base = f.replace(/\.mdx?$/, '');
    return base !== 'index' && base !== 'README';
  });

  const withPosition = entries.map((file) => ({
    file,
    position: parseSidebarPosition(fs.readFileSync(path.join(dir, file), 'utf8')),
  }));

  withPosition.sort((a, b) => {
    if (a.position != null && b.position != null) return a.position - b.position;
    if (a.position != null) return -1;
    if (b.position != null) return 1;
    return a.file.localeCompare(b.file);
  });

  return withPosition.map(
    ({ file }) => `${docPrefix}/${stripNumberPrefix(file.replace(/\.mdx?$/, ''))}`
  );
}
